{
 "title": "Channel Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ibmmq_qmgr_status, k8s_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_channel_status_squash{k8s_instance=\"[[instance]]\"}+0"
    },
    {
     "expr": "ibmmq_channel_status{k8s_instance=\"[[instance]]\"}+0"
    }
   ]
  },
  {
   "title": "Channel Activity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_channel_time_since_msg{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "{{channel}} [{{type}}]"
    },
    {
     "expr": "count by (channel, qmgr)(ibmmq_channel_status{k8s_instance=\"[[instance]]\"})",
     "legendFormat": "Count: {{channel}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Channel Bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_channel_bytes_sent{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Byte Sent: {{channel}}[{{type}}]"
    },
    {
     "expr": "ibmmq_channel_bytes_rcvd{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Byte Rcvd: {{channel}}[{{type}}]"
    }
   ]
  },
  {
   "title": "Channel Messages",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_channel_messages{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Msg: {{channel}} [{{type}}]"
    },
    {
     "expr": "ibmmq_channel_buffers_sent{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Buf Sent: {{channel}}[{{type}}]"
    },
    {
     "expr": "ibmmq_channel_buffers_rcvd{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Buf Rcvd: {{channel}}[{{type}}]"
    },
    {
     "expr": "ibmmq_channel_buffers{k8s_instance=\"[[instance]]\"}"
    }
   ]
  },
  {
   "title": "Network Transfer Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ibmmq_channel_nettime_short{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Short: {{channel}}"
    },
    {
     "expr": "ibmmq_channel_nettime_long{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Long: {{channel}}"
    }
   ]
  },
  {
   "title": "Channel Batches",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_channel_batches{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Batches: {{channel}}"
    },
    {
     "expr": "ibmmq_channel_batchsz_short{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "BatchSz (short): {{channel}}"
    },
    {
     "expr": "ibmmq_channel_batchsz_long{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "BatchSz (long): {{channel}}"
    }
   ]
  },
  {
   "title": "Transmission Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ibmmq_channel_xmitq_time_short{type=\"SENDER\",k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Short: {{channel}}"
    },
    {
     "expr": "ibmmq_channel_xmitq_time_long{type=\"SENDER\",k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Long: {{channel}}"
    }
   ]
  },
  {
   "title": "Channel Status Table Merged",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "ibmmq_channel_attribute_max_inst{type=\"SVRCONN\",k8s_instance=\"[[instance]]\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_attribute_max_instc{type=\"SVRCONN\",k8s_instance=\"[[instance]]\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_cur_inst{type=\"SVRCONN\",k8s_instance=\"[[instance]]\"} + 0",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Channel Attributes table",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "ibmmq_channel_attribute_max_inst{type=\"SVRCONN\",k8s_instance=\"[[instance]]\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_attribute_max_instc{type=\"SVRCONN\",k8s_instance=\"[[instance]]\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_cur_inst{type=\"SVRCONN\",k8s_instance=\"[[instance]]\"} + 0",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Total Active Channels",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": " count(ibmmq_channel_status{k8s_instance=\"[[instance]]\"}) by (qmgr)"
    }
   ]
  }
 ]
}