{
 "title": "Queue Manager Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ibmmq_qmgr_status, k8s_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_status{k8s_instance=\"[[instance]]\"}+0"
    },
    {
     "expr": "ibmmq_qmgr_channel_initiator_status{k8s_instance=\"[[instance]]\"}+0"
    },
    {
     "expr": "ibmmq_qmgr_command_server_status{k8s_instance=\"[[instance]]\"}+0"
    },
    {
     "expr": "ibmmq_qmgr_uptime{k8s_instance=\"[[instance]]\"}"
    },
    {
     "expr": "ibmmq_qmgr_connection_count{k8s_instance=\"[[instance]]\"}+0"
    },
    {
     "expr": "ibmmq_qmgr_max_channels{k8s_instance=\"[[instance]]\"}+0"
    },
    {
     "expr": "ibmmq_qmgr_max_active_channels{k8s_instance=\"[[instance]]\"}+0"
    }
   ]
  },
  {
   "title": "Connection Count (inc. internal processes)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_connection_count{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Connection Count: {{qmgr}}"
    }
   ]
  },
  {
   "title": "Processed Publications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_exporter_publications{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "{{qmgr}}"
    }
   ]
  },
  {
   "title": "FDC Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_mq_fdc_file_count{k8s_instance=\"[[instance]]\"}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "ibmmq_cluster_suspend{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "State"
    }
   ]
  }
 ]
}