{
 "title": "Queue Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ibmmq_qmgr_status, k8s_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message Lifetime",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ibmmq_queue_qtime_short{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "QTime Short: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_qtime_long{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "QTime Long: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Oldest message",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_queue_oldest_message_age{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Oldest msg: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "max(ibmmq_queue_oldest_message_age{k8s_instance=\"[[instance]]\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Put/Get Activity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_queue_mqget_count{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Get: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_qmgr_persistent_message_mqput_count{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Put: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_queue_depth{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Depth: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "(ibmmq_queue_depth{k8s_instance=\"[[instance]]\"} * 100 )/ ibmmq_queue_attribute_max_depth{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "% Depth: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_uncommitted_messages{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Uncom: {{queue}}@@{{qmgr}}"
    }
   ]
  },
  {
   "title": "QFile Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 * ibmmq_queue_qfile_current_size/ibmmq_queue_qfile_max_size{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "Queue: {{queue}}  QMgr: {{ qmgr}}"
    }
   ]
  },
  {
   "title": "Object handles",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ibmmq_queue_input_handles{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "IPPROCS: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_output_handles{k8s_instance=\"[[instance]]\"}",
     "legendFormat": "OPPROCS: {{queue}}@{{qmgr}}"
    }
   ]
  }
 ]
}